### ISSUE TITLE
Youtube dash live audio will download a bunch of chunks instead of the latest ones

### ISSUE THREAD

**Issue by Llorx** [fent/node-m3u8stream#21]
Easy to replicate with ytdl-core:
```
// Monstercat
ytdl("https://www.youtube.com/watch?v=SOvuDzLawpg", {
    quality: "highestaudio",
    filter: "audioonly"
}).on("progress", console.log);
// Pipe to somewhere
```

This will download a lot chunks instantly, and eventually will receive `NaN`s because I guess that YT limits the amount of requests.

**Comment by fent** [comment]
It gives me `NaN`s from the first event. This is an issue with getting the size of a segment, will fix in a bit.

**Comment by fent** [comment]
Not sure about the first issue about downloadingg some chunks instantly. I didn't reproduce that. Feel free to open if there are still issues.

**Comment by Llorx** [comment]
Nice, the `NaN ` problem got fixed (thnx!), but the "download all chunks from start instead of last 3 chunks" still happens. Check this gif:
![gif](https://vgy.me/Pc6ces.gif)

As extra info, the audio bitrate is 128 kbps, each chunk is 5 seconds audio length and in 3-5 seconds running this script created a 16 Mb audio file:
![audio](https://i.imgur.com/wW7VM0i.png)

I cannot tell the audio length because VLC is doing weird things, but way more than 15 seconds. I'm listening for it for 5 minutes now, and if I enter the monstercat link and go to the very start of the live video (as the live stream has DVR enabled), the same song is played, so the script is downloading chunks from the start of the stream instead of the last chunks:
![gif2](https://vgy.me/SImW0f.gif)

I guess that is [the same problem that happened with m3u8](https://github.com/fent/node-m3u8stream/pull/7) some time ago, but with dash now.

**Comment by fent** [comment]
Thanks for the detailed gifs! Wasn't able to reproduce this on my first try, will investigate.

**Comment by fent** [comment]
Ok, deployed a fix. Should be good now, but let me know if things still don't work.

**Comment by Llorx** [comment]
Nice, will try. Thanx!
