### ISSUE TITLE
wrong contentType

### ISSUE THREAD

**Issue by fxp** [fent/node-m3u8stream#24]
I check the contentType of the video file with "file"
the output is just "data"
```
file test.mp4
testtest.mp4: data
```

**Comment by fent** [comment]
Where does the error come from?

**Comment by fxp** [comment]
Just convert a m3u8 to mp4 with 

>     const stream = m3u8stream(url);
>     let videoFile = 'testtest.mp4';
>     stream.pipe(fs.createWriteStream(videoFile));
>     stream.on('progress', (segment, totalSegments, downloaded) => {
>       console.log('m3u8 segment downloaded', segment.num, '/', totalSegments);
>     });
>     stream.on('error', (e) => {
>       reject(e);
>     })
>     stream.on('end', () => {
>       resolve(videoFile);
>     })

when I test the mp4 file with `file testtest.mp4 ` I got "testtest.mp4: data"

**Comment by fent** [comment]
sorry for really late reply, what's the url?
