### ISSUE TITLE
Try to add hls version 7 #EXT-X-MAP:URI

### ISSUE THREAD

**Issue by remi-livescale** [fent/node-m3u8stream#30]
Hi,
I m trying to extend your code. 
I added in your switch case  with : 
```ts
case 'EXT-X-MAP':          
            const initFile = value.match(/(?<=\").+?(?=\")/g)
            this.emit("item", {
              url: initFile[0],
              duration: 2000
              }) 
           break;
```

but it's only read 1 times my chunks

**Comment by fent** [comment]
what does `EXT-X-MAP` do?

**Comment by remi-livescale** [comment]
Hi I finally fix my issues, it was problem with my stream
Here you can see what EXT-X-MAP is :
![image](https://user-images.githubusercontent.com/52050878/59924615-200cca80-9404-11e9-856b-73cb966b32e6.png)


Just by adding one switch more case is working for me
