### ISSUE TITLE
Cannot get the begin option to work

### ISSUE THREAD

**Issue by galipmedia** [fent/node-m3u8stream#46]
I am trying to use this on a VOD from twitch. But no matter what I try to put in the begin parameter it always starts from the start. I've tried everything i can think of even hacking the node module. Can anyone help me track to say 30 minutes into the VOD to start the download?

**Comment by galipmedia** [comment]
I made a pull request after realising twitch VODs do not have EXT-X-PROGRAM-DATE-TIME . Instead they have #ID3-EQUIV-TDTG: (whatever that is)
https://github.com/fent/node-m3u8stream/pull/47

**Comment by galipmedia** [comment]
On closer inspection this time does not correlate with the actual stream start time (comparing with the API) and it does not have Z at the end so I am confused as to how to use it and if it is indeed usable at this point.

**Comment by fent** [comment]
even if it doesn't have a start time, you should still be able to start from a given time, since all the segments are timed. I'll look into this
