### ISSUE TITLE
get the full available buffer

### ISSUE THREAD

**Issue by galipmedia** [fent/node-m3u8stream#59]
Just wondering with an m3u8 for a live stream like this... 
```#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:806
#EXT-X-TARGETDURATION:2
#EXTINF:2.000,
145260000.ts
#EXTINF:2.000,
145440000.ts
#EXTINF:2.000,
145620000.ts
#EXTINF:2.000,
145800000.ts
#EXTINF:2.000,
145980000.ts
#EXTINF:2.000,
146160000.ts
#EXTINF:2.000,
146340000.ts
#EXTINF:2.000,
146520000.ts
```

How can you force it to go back as far as possible? I have tried a few things like, begin: '-16s'. Or maybe these are future .ts files ? I am unfamiliar with m3u8. But the recording is always starting immediately even though i see a default buffer of 20 seconds in the code. Can anyone help me?

**Comment by fent** [comment]
a relative `begin` time is relative from the beginning of the video. try using `begin: 0`.

it doesn't support negative relative numbers to refer to the end of the video

**Comment by galipmedia** [comment]
OMG of all the things i tried I missed the most obvious :( Now I feel stupid! Thanks for your extremely quick reply and great script!

**Comment by fent** [comment]
no problem!
