### ISSUE TITLE
any way to download chuncks in parallel?

### ISSUE THREAD

**Issue by stefanocudini** [fent/node-m3u8stream#65]

**Comment by fent** [comment]
the `chunkReadahead` can do that

https://github.com/fent/node-m3u8stream#m3u8streamurl-options

is that what you mean?

**Comment by stefanocudini** [comment]
mmh it depends on what you mean by preload

**Comment by fent** [comment]
it means they are downloaded ahead of the current segment

**Comment by stefanocudini** [comment]
however... any request is synchronous?

**Comment by fent** [comment]
they are in parallel
