### ISSUE TITLE
TLS error

### ISSUE THREAD

**Issue by stefanocudini** [fent/node-m3u8stream#66]
sometimes in random moments after the download has started I get this error

2 of 71 segments (2.82%) 6.10MB downloadedevents.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)

**Comment by stefanocudini** [comment]
related to this https://github.com/nodejs/node/issues/27916

**Comment by fent** [comment]
this library uses [miniget](https://github.com/fent/node-miniget), retries and reconnects if there's ever an error. maybe try increasing the `maxRetries` option?

since it happens randomly, I don't think there's anything else I can do.

**Comment by stefanocudini** [comment]
many thanks! it works!
