### ISSUE TITLE
Holds open files

### ISSUE THREAD

**Issue by manolan1** [fent/node-m3u8stream#69]
I have an issue where I am doing a simple pipe of an m3u8 stream into a file. 

```
m3u8stream(source)
    .pipe(fs.createWriteStream(file));
```

The process periodically stops, with or without an error (I think the server is getting overloaded at this point, but I'll probably look into that later). Anyway, my process just restarts it unless it repeatedly errors in a short time, after all networks are inherently unreliable!

When the process ends with an error, I believe all is well and the file is properly closed.

However, when the process just ends, the file is held open. I have added some logging to my version of the library and I see that stream.end is never called in this case. I don't know exactly what causes this, so I'm unable to create a test case on a publicly available stream. The only thing I can see is that just before this happens, the process retrieves exactly the same playlist that it retrieved the previous time - same start time and no new segments.

To save me tracking through all the logic, does that seem like something that would cause the download to end? And, if so, should it? If it should, then I think there is a case where stream.end should be called. If not, then it probably just needs to queue the request one more time.

I'm happy to take a further look and mock up the scenario I just described to see if it is the cause, but I'm putting this here in case you immediately look and go "doh!" Plus I don't use nock and I'll have to learn how to mock this scenario in a way that fits with the existing tests ;)

**Comment by fent** [comment]
> The only thing I can see is that just before this happens, the process retrieves exactly the same playlist that it retrieved the previous time - same start time and no new segments.

is this a live playlist that contains different segments and keeps getting refreshed until it prints a `EXT-X-ENDLIST`? I've just looked at the code, and it looks like if during a refresh, there are no new segments, it won't refresh.

on your version, you can test this by adding a call to `onQueueEnd()` on the `parser.on('end',` event

**Comment by manolan1** [comment]
Yes, it is a live stream.

Do you mean `onQueuedEnd`? So, like this?

```
    parser.on('end', () => {
      currPlaylist = null;
      // If we are too ahead of the stream, make sure to get the
      // latest available items with a small buffer.
      if (!addedItems.length && tailedItems.length) {
        tailedItems.forEach((item) => { addItem(item); });
      }

      // Refresh the playlist when remaining segments get low.
      refreshThreshold = Math.max(1, Math.ceil(addedItems.length * 0.01));

      // Throttle refreshing the playlist by looking at the duration
      // of live items added on this refresh.
      minRefreshTime =
        addedItems.reduce(((total, item) => item.duration + total), 0);

      fetchingPlaylist = false;
      onQueuedEnd();
    });

```

That appears to work. I have now checked and previously, the process ended without closing the stream _every_ time a playlist had the same sequence as its predecessor. Now that does not happen: the process continues.

I have also tried my luck at a new test. I don't understand why it is necessary to add the later responses to the `scope` in the `nextTick`, since my reading is that each call removes the interceptor from the list. Anyway, that made this somewhat complicated since I wanted to `replyWithFile` and also call `nextTick`. This may not be the most elegant way to do it. In addition, with the old code, this test fails with a timeout from mocha because the `done` callback is never invoked (since there is no `end` event). While that does detect the problem, it is also not very elegant. Short of starting a timer that _just_ undercuts the mocha timeout, I cannot think of a way to detect the absence of the `end` event!

```
    it('Handle same playlist twice', (done) => {
      let scope = nock('https://priv.example.com')
        .get('/playlist.m3u8')
        .replyWithFile(200, path.resolve(__dirname,
          'playlists/live-1.1.m3u8'))
        .get('/fileSequence2681.ts').reply(() => {
          process.nextTick(passSomeTime1);
          return [200, 'apple'];
        })
        .get('/fileSequence2682.ts').reply(200, 'banana')
        .get('/fileSequence2683.ts').reply(200, 'cherry');

      const passSomeTime1 = () => {
        scope.get('/playlist.m3u8')
          .reply(() => {
            const readFile = fs.readFileSync(path.resolve(__dirname,
              'playlists/live-1.1.m3u8'));
            process.nextTick(passSomeTime2);
            return [200, readFile.toString('utf8')];
          })
      };

      const passSomeTime2 = () => {
        scope.get('/playlist.m3u8')
          .replyWithFile(200, path.resolve(__dirname,
            'playlists/live-1.2.m3u8'))
          .get('/fileSequence2684.ts').reply(200, 'fig')
          .get('/fileSequence2685.ts').reply(200, 'grape');
      };

      let stream = m3u8stream('https://priv.example.com/playlist.m3u8');
      concat(stream, (err, body) => {
        assert.ifError(err);
        scope.done();
        assert.equal(body, [
          'apple',
          'banana',
          'cherry',
          'fig',
          'grape'
        ].join(''));
        done();
      });
    });
```

**Comment by fent** [comment]
thanks for taking a stab at this and adding a test :)

> I don't understand why it is necessary to add the later responses to the `scope` in the `nextTick`, since my reading is that each call removes the interceptor from the list.

if that's the case then I've been writing these tests wrong. if that works for you then great, I can update the rest of the tests that use `nextTick`.


> In addition, with the old code, this test fails with a timeout from mocha because the `done` callback is never invoked (since there is no `end` event). While that does detect the problem, it is also not very elegant. Short of starting a timer that _just_ undercuts the mocha timeout, I cannot think of a way to detect the absence of the `end` event!

wouldn't the new code make the stream end by having the playlist properly refresh?

**Comment by manolan1** [comment]
> thanks for taking a stab at this and adding a test :)
> 
> > I don't understand why it is necessary to add the later responses to the `scope` in the `nextTick`, since my reading is that each call removes the interceptor from the list.
> 
> if that's the case then I've been writing these tests wrong. if that works for you then great, I can update the rest of the tests that use `nextTick`.
> 

This simpler format appears to work:
```
    it('Handle same playlist twice', (done) => {
      let scope = nock('https://priv.example.com')
        .get('/playlist.m3u8')
        .replyWithFile(200, path.resolve(__dirname,
          'playlists/live-1.1.m3u8'))
        .get('/fileSequence2681.ts').reply(200, 'apple')
        .get('/fileSequence2682.ts').reply(200, 'banana')
        .get('/fileSequence2683.ts').reply(200, 'cherry')
        .get('/playlist.m3u8')
        .replyWithFile(200, path.resolve(__dirname,
          'playlists/live-1.1.m3u8'))
        .get('/playlist.m3u8')
        .replyWithFile(200, path.resolve(__dirname,
          'playlists/live-1.2.m3u8'))
        .get('/fileSequence2684.ts').reply(200, 'fig')
        .get('/fileSequence2685.ts').reply(200, 'grape');

      let stream = m3u8stream('https://priv.example.com/playlist.m3u8');
      concat(stream, (err, body) => {
        assert.ifError(err);
        scope.done();
        assert.equal(body, [
          'apple',
          'banana',
          'cherry',
          'fig',
          'grape'
        ].join(''));
        done();
      });
    });

```
In the event that the code does not handle the situation, then it will timeout because `done` is never invoked, rather than giving an assertion error.

> > In addition, with the old code, this test fails with a timeout from mocha because the `done` callback is never invoked (since there is no `end` event). While that does detect the problem, it is also not very elegant. Short of starting a timer that _just_ undercuts the mocha timeout, I cannot think of a way to detect the absence of the `end` event!
> 
> wouldn't the new code make the stream end by having the playlist properly refresh?

Indeed, with the new code, it is all fine. It is just that if it fails, there is no handy message, just a timeout!

**Comment by manolan1** [comment]
Is this the full fix, then?! It certainly seems to work.

Would you like me to create a pull request, or would you prefer to apply this change yourself?

**Comment by fent** [comment]
> Would you like me to create a pull request

that'd be great

thank you for figuring this out
