### ISSUE TITLE
Begin option not working (ytdl-core)

### ISSUE THREAD

**Issue by wildyaboku** [fent/node-m3u8stream#83]
Opening this in place of https://github.com/fent/node-ytdl-core/issues/849.

I'm trying to download livestreams from YouTube, starting from as close to the beginning as possible (up to 4 hours ago?) and continuing until the stream ends. Passing in `{ begin: '0s' }` is not working -- it always starts at around the current time. 

```ts
const stream = ytdl('https://www.youtube.com/watch?v=d5JbMeNWP-w', {
    begin: '0s'
});
```

I see that m3u8stream is being called with the correct options (begin=0s, id=96, parser=m3u8). The `index.m3u8` file being downloaded from YouTube contains this header followed by 7 links:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:2464
#EXT-X-PROGRAM-DATE-TIME:2020-12-30T15:24:34.261+00:00
#EXTINF:5.005,
```

Is there a limitation from YouTube that prevents this, or am I perhaps doing something wrong?
 
Thanks!

**Comment by fent** [comment]
it's a limitation from the format provided by youtube. the playlist above contains only 7 links, they're the latest segments, and each segment is 2 secs long. my guess is, m3u8 playlists are meant to be consumed live.

if you select a dashmpd playlist, it can contain more time. although i checked quickly with one, it was only about 100 minutes of playback

then there are the non-playlist formats. trying these, they only work for 2 secs. these aren't being requested correctly, my guess it they're meant to be used to construct segments out of. but we don't know how to do that yet. this issue tracks that: https://github.com/fent/node-ytdl-core/issues/688

**Comment by wildyaboku** [comment]
Thanks for the information! I'm closing this since it's a limitation. Sadly it looks like the stars just aren't aligning for me. 

I was able to download 4 hours of video with the DashMPD format (137) shown below, but it didn't include audio. 

Interestingly, ytdl-core returned two formats with itag=137, one of which was not DashMPD but still downloaded the full 4 hours. The other non-playlist formats, including 140, only gave the last 2 seconds as you said, so it seems I have no way to get audio unless I'm missing something. 

```
Starting: https://www.youtube.com/watch?v=5qap5aO4i9A
Title: lofi hip hop radio - beats to relax/study to
Author: ChilledCow

Id   Container       Quality      Video    Audio    Bitrate     Live
96   ts              1080p        √        √        2.5 MB      √ HLS
95   ts              720p         √        √        1.5 MB      √ HLS
94   ts              480p         √        √        800 kB      √ HLS
93   ts              360p         √        √        500 kB      √ HLS
92   ts              240p         √        √        150 kB      √ HLS
91   ts              144p         √        √        100 kB      √ HLS
137  mp4             1080p        √                 4.35 MB     √ DashMPD
137  mp4             1080p        √                 4.35 MB     √
136  mp4             720p         √                 2.33 MB     √
135  mp4             480p         √                 1.17 MB     √
134  mp4             360p         √                 646 kB      √
133  mp4             240p         √                 258 kB      √
160  mp4             144p         √                 124 kB      √
140  mp4                                   √        144 kB      √
```

Thanks for the help and cheers!
