### ISSUE TITLE
Any way to combine separate audio & video streams

### ISSUE THREAD

**Issue by Benny739** [fent/node-m3u8stream#84]
Is there any way to combine audio and video streams when they are separate?

**Comment by redbrain** [comment]
You can use ffmpeg, available through your computer or the node library ffmpeg-static.

**Comment by MGPlayzYT** [comment]
Here is an example that will do that:
https://github.com/fent/node-ytdl-core/blob/master/example/ffmpeg.js

**Comment by Benny739** [comment]
Thanks for your help
