### ISSUE TITLE
Twitch stream m3u8s to mp4 chucks not working

### ISSUE THREAD

**Issue by mikemilla** [fent/node-m3u8stream#91]
Looks like when trying to grab a twitch stream, the video will export, but the video is not playable in anything other than VLC player, or at least that looks like the only one that works for me.

Maybe there is an issue with the mp4 metadata or something that prevents it from playing in other players?

Here is what I am running:

    const fs = require('fs');
    const readline = require('readline');
    const m3u8stream = require('m3u8stream')

    let index = -1;
    const url = "..." // You can get this using this package: https://www.npmjs.com/package/twitch-get-stream

    const stream = m3u8stream(url);

    function saveNextBatch() {
        stream.unpipe()
        index++
        stream.pipe(fs.createWriteStream(`media_${index}.mp4`))
    }

    saveNextBatch()

    stream.on('progress', (segment, totalSegments, downloaded) => {

        const percentage = (segment.num / totalSegments * 100).toFixed(2)

        readline.cursorTo(process.stdout, 0);
        process.stdout.write(
            `${segment.num} of ${totalSegments} segments ` +
            `(${percentage}%) ` +
            `${(downloaded / 1024 / 1024).toFixed(2)}MB downloaded`)

        if (percentage >= 100) {
            saveNextBatch()
        }

    })

**Comment by TimeForANinja** [comment]
m3u8 can serve encodings that are not compatible with mp4
vlc is pretty good at still playing stuff like that
did you check for the delivered encoding? sth. like `EXT-X-STREAM-INF` should be present
you could also use ffprobe to check for the actual container and encoding

**Comment by fent** [comment]
yep, m3u8stream concatenates every chunk together. it doesn't transcode.

btw, `percentage` is a string

>     if (percentage >= 100) {
>         saveNextBatch()
>     }
